### ISSUE TITLE
Problem while using `add_missing_transaction_fees()`

### ISSUE THREAD

**Issue by cristobaltapia** [probstj/ccGains#2]
I tried using the function `th.add_missing_transaction_fees(raise_on_error=True)` but I am getting an error that says that a withdrawal is lower than the previous deposit: (fake BTC data)  

`ValueError: The withdrawal from 2017-09-19 13|33| 14+00:00 (0.4110000 BTC, Wallet A) is lower than the first deposit (2017-09-22 21:45:43+00:00, 0.5000000 BTC, Wallet B) following it.`

The problem is that the function is trying to couple the first withdrawal with the next deposit, while actually the first withdrawal corresponds to a payment (i.e. I'm not getting it back to any wallet).
Actually, right after the deposit a withdrawal is listed, which corresponds to the actual source of the deposit. This are the relevant movements: (fake BTC data)

```
...
20 Abhebung   19.09.2017, 13:33:14 0,00000000 BTC 0,41100000 BTC 0,00000000 BTC Wallet A
21 Einzahlung 22.09.2017, 21:45:43 0,50000000 BTC 0,00000000 0,00000000 BTC Wallet B
...
23 Abhebung   22.09.2017, 21:45:43 0,00000000 BTC 0,50096500 BTC 0,00000000 BTC Wallet A
...
``` 

So, as can be seen, the transaction No. 20 is considered to go to the No. 21, when actually the No. 23 should be the one connected to the No. 21. They are happening at the same time, whilst the other one occurred a few days earlier.

**Comment by cristobaltapia** [comment]
Thanks for that fix ;)

The problem with payments is not easy, because the exported data only differentiates between in and out. The transaction 20 was made with an 'Electrum Wallet' I had before the Trezor. There it is the same: you can only tell if the BTCs come in or go out. The user can add a comment for each transaction, which could be e.g. 'Payment ...'. But the Trezor does not include the possibility of adding comments to the transactions, so it wouldn't work there. 

Maybe a first approach to identifying payments can be to look for withdrawals of crypto currencies that have no matching deposit in another wallet. Still, the user would have to check if everything is OK. I'll try to think more about it.

**Comment by cristobaltapia** [comment]
Regarding the `pay` method, as I understand it, I have to delete the respective line in the `*.csv` file, right (to not account for it twice)? And then the transaction has to be manually added. It could be useful to maybe just define the numbers corresponding to the payments so that they can be correctly accounted for.

**Comment by probstj** [comment]
Yes, I think it is complaining because it already withdrew that exact amount because it interpreted the payment in the csv as withdrawal. That withdrawal should be logged just before the Error is raised, can you see it?

I think the clearest would be to change the kind to 'Payment' in the trades list already before the trades are processed. That would be by simply editing the *.csv before importing. (Later we could add a special function that the user can call with numbers or dates of payments, then the corresponding trades could be marked as payments). Then it's necessary to add a new case in `bags.process_trade`.  Best to add it before line #914 (before the line with `elif not trade.buycur or (trade.buyval == 0...`), simply: `elif trade.kind == 'Payment' and (not trade.buycur or (trade.buyval == 0)):` then call `self.pay`... Or maybe it's enough to just exclude payments on line #914 with `trade.kind!='Payment'`, then it will be handled by the last `else:`, were `self.pay` will be called? I'll try that tomorrow. :)

**Comment by cristobaltapia** [comment]
The Electrum Wallet csv-file doesn't have a column for the `kind` variable explicitly (that is why I look for the sign of the transferred amount to deduce whether it is a withdrawal or deposit). So, in this particular case, editing the csv-file means adding a new column, which would make it incompatible with the defined TPLOC dictionary. So the best solution is for the user to handle the payment manually with the function `pay()`.

Of course, the better solution would be what you propose, i.e. a special function that can be called by the user with the number of the transaction to be defined as a payment.

**Comment by probstj** [comment]
With the latest commit, if you have a transaction with `Trade.kind == "payment"` it will be properly handled. If you can't set the `kind` in the csv, can you manually change the kind in the `TradeHistory.tlist` before processing with `Bags.process_trade`?

**Comment by cristobaltapia** [comment]
Yes, it works when I edit the corresponding item in `TradeHistory.list` manually.
